kind: pipeline
type: docker
name: default

steps:
- name: build
  image: fedora
  commands:
    - dnf install -y git cmake SDL2-devel
    - git submodule update --recursive --init
    - cmake -E make_directory ./build
    - cd ./build
    - cmake -S .. -B .
    - make
